version: "3.9"
services:
  myapp:
    build: .
    ports:
      - "3000:3000"
    links:
      - monguito
    environment:
      - USERNAMEDB=alexis
      - PASSWORD=password123
      - PORT=3000
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alexis
      - MONGO_INITDB_ROOT_PASSWORD=password123
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data
volumes:
  mongo-data: